<?php include ("header.html"); ?>
<title>Interne Abl&auml;ufe bei Polizei und Stadt Frankfurt</title>
</head>
<?php include ("menu.html"); ?>
<p>Diese Seite stellt nur einige Hintergrundinformationen bereit, diese sind f&uuml;r die allt&auml;gliche Arbeit normalerweise nicht erforderlich.</p>
<h1 id="ausschreibung_abschleppvertraege">Ablauf der Verwaltungspanne bei Ausschreibung der Abschleppvertr&auml;ge</h1>
<p>Durch eine "Verwaltungspanne" <a href="#quellen_2"><sup>2</sup></a> hat die Stadt Frankfurt aktuell keinen g&uuml;ltigen Vertrag mit Abschleppunternehmen und "darf" daher nur eingeschr&auml;nkt abschleppen lassen um Klagen im Hinblick auf das europ&auml;ische Vergaberecht aus dem Weg zu gehen. <a href="#quellen_2"><sup>2</sup></a> <a href="#quellen_3"><sup>3</sup></a> Am 07.03.2018<a href="#quellen_4"><sup>4</sup></a> wurde berichtet, dass ab April 2018 wieder vermehrt abgeschleppt werden solle. Am 11.04.2018 wurde berichtet<a href="#quellen_5"><sup>5</sup></a>, dass nun etwas mehr Abschleppunternehmen beauftragt werden k&ouml;nnen. Die "richtigen" Abschleppvertr&auml;ge sind nach wie vor nicht aktiv. Am 19.10.2018 teilte die Stadtverwaltung mit <a href="#quellen_6"><sup>6</sup></a>, dass man ab dem 05.11.2018 wieder ganz normal abschleppen k&ouml;nne weil die Abschleppvertr&auml;ge ab dann wieder greifen. Bereits am 05.11.2018 gab es einen entsprechenden Bericht <a href="#quellen_7"><sup>7</sup></a>, wonach die angek&uuml;ndigten Vertr&auml;ge doch nicht gelten sollen und es noch einige Wochen dauern kann. Am 06.03.2019 wurde auf Nachfrage bekanntgegeben, dass es nach wie vor lediglich &Uuml;bergangsvertr&auml;ge gibt und im Jahr 2018 im Vergleich zu den Vorjahren &uuml;ber 50% weniger Abschleppvorg&auml;nge durchgef&uuml;hrt wurden.<a href="#quellen_8"><sup>8</sup></a> Am 29.04.2019 teilte die Verwaltung in einer Pressemitteilung mit, dass man zuk&uuml;nftig auf die europaweite Ausschreibung f&uuml;r Abschleppvertr&auml;ge verzichten und das Konzept einer eigenen Vermittlungsstelle beibehalten wird.<a href="#quellen_9"><sup>9</sup></a></p>

<h1 id="schutz_orga_abschleppen">Schutzpolizei: Organisation der Abschleppvorg&auml;nge</h1>
<p>Die Polizei Frankfurt organisiert ihre Abschleppauftr&auml;ge &uuml;ber die <a href="http://www.abschleppdienste-frankfurt.de">Firma Noss</a> <a href="#quellen_1"><sup>1</sup></a>.</p>

<h1 id="stadt_orga_abschleppen">Stadt Frankfurt: Organisation der Abschleppvorg&auml;nge</h1>
<p>Normalerweise schlie&szlig;t die Stadt Frankfurt Rahmenvertr&auml;ge mit Abschleppunternehmen, die dann von den st&auml;dtischen Beh&ouml;rden bei Bedarf angefordert werden k&ouml;nnen. Durch die <a href="#ausschreibung_abschleppvertraege">Verwaltungspanne bei der Ausschreibung der Abschleppvertr&auml;ge</a> m&uuml;ssen aktuell die Abschleppfirmen im Rotationsverfahren einzeln beauftragt werden. <a href="#quellen_10"><sup>10</sup></a> <a href="#quellen_11"><sup>11</sup></a>. Zuk&uuml;nftig soll es eine "ausgelagerte Zentrale" geben, die die st&auml;dtischen Abschleppauftr&auml;ge zentral verwaltet<a href="#quellen_11"><sup>11</sup></a>. Wer diese "ausgelagerte Zentrale" betreibt oder wann sie den Betrieb aufnehmen soll, ist noch offen.</p>

<h1 id="quellennachweise">Quellennachweise</h1>
<sup id="quellen_1">1</sup> <a href="https://twitter.com/Polizei_Ffm/status/936205764066242560" target="_blank" rel="noopener">Offizielle Antwort der Polizei Frankfurt auf Twitter</a>, &uuml;ber <a href="https://web.archive.org/web/20190306133219/https:/twitter.com/Polizei_Ffm/status/936205764066242560">Web Archive</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_2">2</sup> <a href="http://www.hessenschau.de/wirtschaft/frankfurt-kann-nicht-mehr-alle-falschparker-abschleppen-lassen,abschleppdienste-frankfurt-100.html" target="_blank" rel="noopener">Bericht von hessenschau.de vom 17.01.18</a>, nur noch &uuml;ber das <a href="https://web.archive.org/web/20180323064232/http://www.hessenschau.de/wirtschaft/frankfurt-kann-nicht-mehr-alle-falschparker-abschleppen-lassen,abschleppdienste-frankfurt-100.html">Web Archive abrufbar</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_3">3</sup> <a href="https://www.hr.de/presse/radio/hrinfo/2018/wegen-ausschreibung-stadt-frankfurt-laesst-derzeit-weniger-abschleppen-,weniger-abschleppen-in-frankfurt100.html" target="_blank" rel="noopener">Bericht von hr.de vom 17.01.18</a>, nicht mehr abrufbar, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_4">4</sup> <a href="http://www.faz.net/aktuell/rhein-main/bald-wieder-mehr-abschleppdienste-auf-frankfurts-pflaster-15481792.html" target="_blank" rel="noopener">Bericht von faz.net vom 07.03.18</a>, &uuml;ber <a href="https://web.archive.org/web/*/http://www.faz.net/aktuell/rhein-main/bald-wieder-mehr-abschleppdienste-auf-frankfurts-pflaster-15481792.html">Web Archive</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_5">5</sup> <a href="https://www.fnp.de/lokales/frankfurt-wird-wieder-mehr-abgeschleppt-10404765.html" target="_blank" rel="noopener">Bericht von fnp.de vom 11.04.18</a>, &uuml;ber <a href="https://web.archive.org/web/*/https://www.fnp.de/lokales/frankfurt-wird-wieder-mehr-abgeschleppt-10404765.html">Web Archive</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_6">6</sup> <a href="https://www.hr.de/presse/radio/hrinfo/2018/frankfurt-hat-ab-november-wieder-abschlepp-unternehmen-unter-vertrag-,hr-info-stickoxid-belastung-frankfurt-104.html" target="_blank" rel="noopener">Bericht von hr.de vom 19.10.18</a>, &uuml;ber <a href="https://web.archive.org/web/*/https://www.hr.de/presse/radio/hrinfo/2018/frankfurt-hat-ab-november-wieder-abschlepp-unternehmen-unter-vertrag-,hr-info-stickoxid-belastung-frankfurt-104.html">Web Archive</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_7">7</sup> <a href="https://www.ffh.de/nachrichten/hessen/rhein-main/toController/Topic/toAction/show/toId/172675/toTopic/weitere-schonzeit-fuer-falschparker-in-frankfurt.html" target="_blank" rel="noopener">Bericht von ffh.de vom 05.11.18</a>, nicht mehr abrufbar, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_8">8</sup> <a href="https://www.fr.de/frankfurt/falschparker-werden-haeufig-nicht-belangt-11826245.html" target="_blank" rel="noopener">Bericht von fr.de vom 06.03.19</a>, &uuml;ber <a href="https://web.archive.org/web/20190306132953/https://www.fr.de/frankfurt/falschparker-werden-haeufig-nicht-belangt-11826245.html">Web Archive</a>, zuletzt gepr&uuml;ft am 06.03.2019 14 Uhr
<br>
<sup id="quellen_9">9</sup> <a href="https://frankfurt.de/sixcms/detail.php?id=8440&_ffmpar[_id_inhalt]=35421125" target="_blank" rel="noopener">Pressemitteilung der Stadt Frankfurt vom 29.04.2019</a>, nur noch &uuml;ber <a href="https://web.archive.org/web/*/https://frankfurt.de/sixcms/detail.php?id=8440&_ffmpar[_id_inhalt]=35421125">Web Archive</a> abrufbar, zuletzt gepr&uuml;ft am 02.03.2020 10 Uhr
<br>
<sup id="quellen_10">10</sup> <a href="https://www.fr.de/frankfurt/frankfurt-mehr-anzeigen-gegen-falschparker-zr-13055099.html" target="_blank" rel="noopener">Bericht von fr.de vom 01.10.2019</a>, &uuml;ber <a href="https://web.archive.org/web/*/https://www.fr.de/frankfurt/frankfurt-mehr-anzeigen-gegen-falschparker-zr-13055099.html">Web Archive</a>, zuletzt gepr&uuml;ft am 04.10.2019 20 Uhr
<br>
<sup id="quellen_11">11</sup> <a href="https://www.stvv.frankfurt.de/download/B_314_2019.pdf" target="_blank" rel="noopener">Magistratsbericht B 314/2019</a>, &uuml;ber <a href="https://web.archive.org/web/*/https://www.stvv.frankfurt.de/download/B_314_2019.pdf">Web Archive</a>, zuletzt gepr&uuml;ft am 04.10.2019 20 Uhr

<?php include ("footer.html"); ?>
